id: opecha:P009415
initial_creation_type: ocr
source_metadata:
  id: bdr:W1KG25891
  title: ལས་ཞུགས་མི་སྣ་བསྡུ་ལེན་གྱི་བོད་ཡིག་རྒྱུགས་ལེན་བསྐྱར་སྦྱངས་གཏན་ཁེལ་བསླབ་དེབ་དགོས་འདོད་དཔལ་སྟེར།
  volume: ''
  author: ''
