id: P009415
initial_creation_type: ocr
source_metadata:
  id: bdr:W1KG25891
  title: ལས་ཞུགས་མི་སྣ་བསྡུ་ལེན་གྱི་བོད་ཡིག་རྒྱུགས་ལེན་བསྐྱར་སྦྱངས་གཏན་ཁེལ་བསླབ་དེབ་དགོས་འདོད་དཔལ་སྟེར།
  author: ''
  volumes:
    fb8421d9d40e40ca8bb5b45faa60e6cd:
      image_group_id: I1KG25893
      title: ''
      volume_number: 1
      total_pages: 396
      base_file: v001.txt
