id: IF1902233
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-26T22:00:16+00:00'
last_modified: '2022-06-08T10:52:27.589769+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W1KG25891
  title: ལས་ཞུགས་མི་སྣ་བསྡུ་ལེན་གྱི་བོད་ཡིག་རྒྱུགས་ལེན་བསྐྱར་སྦྱངས་གཏན་ཁེལ་བསླབ་དེབ་དགོས་འདོད་དཔལ་སྟེར།
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: true
  base:
    81F0:
      image_group_id: I1KG25893
      title: ''
      total_pages: 396
      order: 1
      base_file: 81F0.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
